const mongoose=require('mongoose');
const ProviderSchema=new mongoose.Schema(
    {
        name:{
            type:String,
            required:true,
            unique:true
        },
        address:{
            type:String,
            required:true
        },
        contact_no:[
            {
                type:String
            }
        ],
        email:{
            type:String,
            required:true,
            lowercase:true,
            unique:true
        },
        rating:{
            type:Number,
            default:0
        },
        bank_acc_no:{
            type:String,
            required:true,
            unique:true
        },
        owner:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'Owner',
            required:true
        },
        service:[
            {
                type:mongoose.Schema.Types.ObjectId,
                ref:'Service',
                required:true
            }
        ],
        membership:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'Membership',
            required:true
        },
        workingRange:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'WorkingRange',
            required:true
        },
        joined_at:{
            type:Date,
            required:true
        },
        state:{
            type:String,
            required:true,
            lowercase:true,
            default:'registered',
            enum:['registered','approved','blocked']
        }
    }
);
const ServiceProvider=mongoose.model('ServiceProvider',ProviderSchema);
module.exports = ServiceProvider;
